const { PrismaClient } = require('@prisma/client')
const p = new PrismaClient()
p.user.findMany({ select: { id: true, email: true, role: true, provider: true } })
  .then(u => { console.log(JSON.stringify(u, null, 2)); return p.$disconnect() })
  .catch(e => { console.error(e); return p.$disconnect() })
